# Generated by Django 5.2.7 on 2025-10-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='イメージ画像'),
        ),
    ]
